### PR TITLE
Dlopen: COCREATE; START; CALL_JQ coex; TAIL_OUT;

### PR DESCRIPTION
**Pull request by leonid-s-usov**
I'll be pushign to this pull request as I proceed. 

This is what I have so far, but I plan to actually have the thing running by tomorrow

### CODE REVIEW

**Comment by leonid-s-usov** [comment]
check-this-shit-out!

**Comment by leonid-s-usov** [comment]
this branch properly runs `echo "1\n2\n3" | ./jq '.'`, I'm done with it ;)

**Comment by nicowilliams** [comment]
```
-OP(CALL_JQ, UFUNC, 1, 1)
-OP(RET, NONE, 1, 1)
-OP(TAIL_CALL_JQ, UFUNC, 1, 1)
+OP(CALL_JQ, UFUNC, 0, 0)
+OP(RET_JQ, NONE, 0, 0)
+OP(TAIL_CALL_JQ, UFUNC, 0, 0)
```
what's up with that?

**Comment by nicowilliams** [comment]
```+  block main_loop = BLOCK (
+    gen_op_simple(START),
+    $3, // call_main
+    gen_op_simple(TAIL_OUT)
+  );
```
So we still have a `START`?

**Comment by nicowilliams** [comment]
```
+  // if this instruction is copied,
+  // the info about the copy is saved here
+  // this allows for post processing to rebind targets or such
+  // the context is used as versioning to identify
+  // instructions which were copied whithin a particular context
+  // POLICY: assign (don't free either target or dest!)
+  struct {
+    void* context;
+    inst* dest;
+  } copy;
```

What's that mean, `POLICY: assign (don't free either target or dest!)`?

**Comment by nicowilliams** [comment]
A "marker" is just a sort of no-op with some semantics?

**Comment by nicowilliams** [comment]
```+            void* ctx = (void*)random();
```

Ohhh, I think I get that.  But why not use the address of a stack variable?  It'd probably be safer than `random()` (which is garbage).

**Comment by nicowilliams** [comment]
```
   errors += expand_call_arglist(&b, args, env);
-  b = BLOCK(b, gen_op_simple(RET));
```

~~OK, so now when we run off the end of bytecode that's an implied `RET`.  I guess I'll see that when I get to `src/execute.c`.~~

**Comment by nicowilliams** [comment]
~~You've left stray `printf()`s in `src/execute.c`...~~

**Comment by nicowilliams** [comment]
```
+    case OUT: {
+      jv value = stack_pop(jq);
+      stack_save(jq, pc - 1, stack_get_pos(jq));
+      return value;
+    }
+    case ON_BACKTRACK(OUT): {
+      // stop backtracking,
+      // move on
+      break;
+    }
```

Appears to be dead code -- `OUT` is not generated anywhere, unless I'm missing some magic.

**Comment by nicowilliams** [comment]
OK!  I believe I get it.  I'll play with it.  I'll add the handle->VM pointer as well to make handle cleanup safe.  I'll merge this.  Then I can finish the I/O bits and we can be done.

Thank you so much @leonid-s-usov!

**Comment by leonid-s-usov** [comment]
> ```
> -OP(CALL_JQ, UFUNC, 1, 1)
> -OP(RET, NONE, 1, 1)
> -OP(TAIL_CALL_JQ, UFUNC, 1, 1)
> +OP(CALL_JQ, UFUNC, 0, 0)
> +OP(RET_JQ, NONE, 0, 0)
> +OP(TAIL_CALL_JQ, UFUNC, 0, 0)
> ```
> 
> 
> what's up with that?

This makes more sense when debugging the stack. Check out my updated stack tracing.
The idea is, instructions which don't modify stack vars shouldn't declare they do. Technically, `0,0` `1,1`, `2,2`, `120,120` are equivalent in terms that the stack doesn't grow or shrink. However, if the values won't ever change I prefer to see that in my trace, which will not mark the top of the stack as the **input** to the instruction

**Comment by leonid-s-usov** [comment]
> ```
> +    gen_op_simple(START),
> +    $3, // call_main
> +    gen_op_simple(TAIL_OUT)
> +  );
> ```
> 
> 
> So we still have a `START`?

Yes, START is there, and it's important: it contains the logic dealing with the initial value - the first `.`. It works almost the same in main and in coroutine - the small difference is due to backward compatibility case of how main is written. 

I believe we can get rid of that small difference but that will imply rewriting main.c, which doesn't seem to be in the scope

**Comment by leonid-s-usov** [comment]
> A "marker" is just a sort of no-op with some semantics?

Marker, like other 0-length instructions, are used during first phase of compilation and linking, but are not making it to the byte code. Another example of such instruction would be CLOSURE_PARAM and CLOSURE_CREATE, which only carry the required metadata for the final compilation phase.

MARKER is just bare instruction without usage of additional fields like target or argils or whatnot. In this case TOP is the marker of the main module code, so any logic that relied on detection main by this instruction is still working, but the instruction isn't taking space.

**Comment by leonid-s-usov** [comment]
> Ohhh, I think I get that.  But why not use the address of a stack variable?  It'd probably be safer than `random()` (which is garbage).

Here and in other places, would be great if you commented on the committed file changes, would be easier to understand the context.

I was thinking about stack variable, which is why I used `void *` as the type, but then I remembered that stack is reused between calls. So the same address could theoretically be assigned to a local variable at two different invocations - especially, if you would call this function in a loop.

Eventually, I've realised that random() is my best choice. Maybe we should change the type of that value, we may even want to call it `verifier`, you know ;)

**Comment by leonid-s-usov** [comment]
> ```
> +    case OUT: {
> +      jv value = stack_pop(jq);
> +      stack_save(jq, pc - 1, stack_get_pos(jq));
> +      return value;
> +    }
> +    case ON_BACKTRACK(OUT): {
> +      // stop backtracking,
> +      // move on
> +      break;
> +    }
> ```
> 
> 
> Appears to be dead code -- `OUT` is not generated anywhere, unless I'm missing some magic.

Oh, right! `output` inlined builtin was supposed to inject it, but looks like I've accidentally removed that definition when working on the builtins. Should be added to `public_inlines`

**Comment by leonid-s-usov** [comment]
Also, I haven't yet worked on the jq coded builtins for `yield` and `exchange` or whatever

**Comment by nicowilliams** [comment]
> I was thinking about stack variable, which is why I used void * as the type, but then I remembered that stack is reused between calls. So the same address could theoretically be assigned to a local variable at two different invocations - especially, if you would call this function in a loop.

So use a global counter...

**Pull request merged**
